---
title: "Lab 6"
author: "Nene Diallo"
Group: "Arifa Begum, Maria Camile, Leo Alcaide, Sun wo Kim" 
date: "2024-10-27"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(haven)
library(forcats)
load("~/Desktop/ACS_2021_couples.RData")
View(acs2021_couples)

```

```{r}
#Subgroup:

#This analysis aims to examine the relationship between income levels and the age differences reported by couples, with a focus on household income and age. Specifically, I will investigate whether different age groups in the labor force exhibit larger age gaps in their relationships compared to those who are not in the labor force, using a 90% confidence level for the statistical tests.


acs2021_couples$age_diff <- acs2021_couples$AGE - acs2021_couples$h_age
summary(acs2021_couples$AGE[(acs2021_couples$SEX == "Female")&(acs2021_couples$h_sex == "Male")])
summary(acs2021_couples$h_age[(acs2021_couples$SEX == "Female")&(acs2021_couples$h_sex == "Male")])

acs_subgroup <- acs2021_couples %>%
  mutate(income_midpoint = case_when(
    HHINCOME < 25000 ~ 12500,
    HHINCOME >= 25000 & HHINCOME < 35000 ~ 30000,
    HHINCOME >= 35000 & HHINCOME < 50000 ~ 40000,
    HHINCOME >= 50000 & HHINCOME < 75000 ~ 62500,
    HHINCOME >= 75000 & HHINCOME < 100000 ~ 82500,
    HHINCOME >= 100000 & HHINCOME < 150000 ~ 125000,
    HHINCOME >= 150000 & HHINCOME < 200000 ~ 175000,
    HHINCOME >= 200000 ~ 225000,
    TRUE ~ NA_real_ ))
View(acs_subgroup)

acs_subgroup1 <- acs_subgroup %>%
 
   filter(AGE >= 25 & AGE <= 85, WKSWORK2 > 4, UHRSWORK >= 35)

View (acs_subgroup1)

```

```{r}
 model_1 <- lm((AGE - h_age) ~ income_midpoint, data = acs_subgroup1)
summary(model_1)
confint(model_1, level = 0.90)
require(AER)

# subset in order to plot...
NNobs <- length(acs_subgroup1$income_midpoint)
set.seed(12345) # just so you can replicate and get same "random" choices
graph_obs <- (runif(NNobs) < 0.1) # so something like just 1/10 as many obs
dat_graph <-subset(acs_subgroup1,graph_obs) 

plot(income_midpoint ~ jitter(AGE - h_age, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), 
     ylim = c(0,120000), data = acs_subgroup1)

#ALT Hyp: There is a relationship between income levels and age differences in couples, with labor force status influencing age gaps.
#Null Hyp: There is no relationship between income levels and age differences in couples.
# t-stat: 14.560 
#p-value: <2e-16
#Conf int: (-3.896278e-01) , (-3.105302e-01)
#Conclusion:At the 90% confidence level, we reject the null hypothesis, indicating a significant relationship between household income levels and age differences in couples. Specifically, as the income midpoint increases, the age difference between partners decreases, suggesting a negative relationship. This supports the hypothesis that different age groups in the labor force exhibit significant differences in age gaps compared to those not in the labor force.

```

```{r}

````

```{r}
acs_subgroup1.2 <- acs2021_couples %>% filter((AGE >= 25) & (AGE <= 55) &
(SEX == "Male") & (FOODSTMP = 2))
ggplot(data = acs_subgroup1.2, mapping = aes(x = AGE, y = FOODSTMP)) + geom_smooth(method = "lm", color ='blue') + theme_economist() + labs (title = "Age and Food Stamps for men", y = " Foodstamps", x = "Age")
acs_subgroup2 <- acs_subgroup %>% filter((AGE >= 25) & (AGE <= 55) &
(SEX == "Female") & (FOODSTMP = 2))
ggplot(data = acs_subgroup2, mapping = aes(x = AGE, y = FOODSTMP)) + geom_smooth(method = "lm", color = 'red') + theme_economist() + labs (title = "Age and Food Stamps for women", y = " Foodstamps", x = "Age")

model_2 <- lm((AGE - h_age) ~ I(SEX == 'Male') + I(FOODSTMP == 2), data = acs_subgroup1.2)
summary (model_2)
# Confidence interval for model_1
confint(model_1, level = 0.95)


# Null Hypothesis (H0): Women use food stamps more than men (W > M).
# Alternative Hypothesis (H1): Women do not use food stamps more than men (W ≤ M).
#P-vaLue: < 2e-16 
#T-stat: -9.796
#Confint: [-0.3972, -0.3029]

#CONCLUSUON: Since the p-value is extremely small, the t-statistic is large, and the confidence interval does not contain zero, we reject the null hypothesis. This means we have strong evidence to conclude that women do not use food stamps more than men.

````


```{r}
# FINAL PROJECT

# For my final project, I would like to focus on entrepreneurship in developing countries,  particularly in sub-Saharan Africa. The project will explore the unique challenges and opportunities faced by entrepreneurs in this region, considering factors such as economic conditions, access to resources, funding availability, and other critical barriers. Through data analysis, I aim to highlight key trends, identify growth sectors, and discuss potential strategies to support sustainable entrepreneurial growth that can drive economic development and job creation in these communities.

#Articles: I am not on two articles yet so i might change these but I will be using Gali data for this project. 

# 1. Landscape Study of Accelerators and Incubators in East Africa: https://www.galidata.org/publications/the-accelerator-and-incubator-landscape-in-east-africa/

#2. A measure of entrepreneurial bricolage behavior: https://www.emerald.com/insight/content/doi/10.1108/IJEBR-11-2015-0256/full/html?skipTracking=true
`````








